server.port: 8082

app.oauth.uri: http://keycloak:8080

# We can use one of these properties
spring.security.oauth2.resourceserver.jwt:
#  issuer-uri: http://localhost:8080/auth/realms/katarinazart
  jwk-set-uri: ${app.oauth.uri}/auth/realms/katarinazart/protocol/openid-connect/certs

---
spring:
  config:
    activate:
      on-profile: local

app.oauth.uri: http://localhost:8080