server:
  port: 8090

app:
  routes:
    uri:
      users-api: http://users-service:8080
      photos-api: http://photos-service:8080
      albums-api: http://albums-service:8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: usersApi
          uri: ${app.routes.uri.users-api}/users/**
          predicates:
            - Path=/users/**
            - Method=POST,PUT,GET,DELETE
          filters:
            - RemoveRequestHeader=Cookie
        - id: albumsApi
          uri: ${app.routes.uri.albums-api}/albums/**
          predicates:
            - Path=/albums/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: photosApi
          uri: ${app.routes.uri.photos-api}/photos/**
          predicates:
            - Path=/photos/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

---
spring:
  config:
    activate:
      on-profile: local

app:
  routes:
    uri:
      users-api: http://localhost:8081
      photos-api: http://localhost:8083
      albums-api: http://localhost:8082




