server:
  port: 8050

logging:
  level:
    net.shyshkin: debug

app.redirect.host.uri: http://localhost:${server.port}

app.oauth.uri: http://keycloak:8080
app.oauth.baseUri: ${app.oauth.uri}/auth/realms/katarinazart/protocol/openid-connect

spring:
  security:
    oauth2:
      client:
        registration:
          photo-app-web-client:
            clientId: photo-app-webclient
            clientSecret: 74ef0a61-f3b5-427c-a450-09a5d1b6f192
            scope:
              - openid
              - profile
              - roles
            redirectUri: ${app.redirect.host.uri}/login/oauth2/code/photo-app-webclient
            authorizationGrantType: authorization_code

        provider:
          photo-app-web-client:
            authorizationUri: ${app.oauth.baseUri}/auth
            tokenUri: ${app.oauth.baseUri}/token
            jwkSetUri: ${app.oauth.baseUri}/certs
            userInfoUri: ${app.oauth.baseUri}/userinfo
            userNameAttribute: preferred_username

---
spring:
  config:
    activate:
      on-profile: local

app.oauth.uri: http://localhost:8080