server:
  port: 8000

logging:
  level:
    net.shyshkin: debug

app.client.baseUri: "http://127.0.0.1:8080"

app.auth-server:
  provider:
    issuer: "http://auth-server:8000"
  clients:
    - client-id: client1
      client-secret: ${CLIENT_SECRET:myClientSecretValue}
      redirect-uris:
        - "${app.client.baseUri}/login/oauth2/code/orders-web-oauth-client"
        - "${app.client.baseUri}/authorized"
      scopes: openid,read

---
spring:
  config:
    activate:
      on-profile: local
app.auth-server:
  provider:
    issuer: "http://localhost:8000"