server:
  port: 8051

logging:
  level:
    net.shyshkin: debug

---
spring:
  config:
    activate:
      on-profile: facebook
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 200469625293049
            clientSecret: ${FACEBOOK_CLIENT_SECRET}

---
spring:
  config:
    activate:
      on-profile: google
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 57502764787-df6bk8i3vlsdmikgvq84tf981refqtif.apps.googleusercontent.com
            clientSecret: ${GOOGLE_CLIENT_SECRET}

---
spring:
  config:
    activate:
      on-profile: github
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: some_val
            clientSecret: some_val

