version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

# Open http://localhost:8080/auth and login as user 'admin' with password 'Pa55w0rd'.
  keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./../../user-storage-provider/target/my-remote-user-storage-provider.jar:/opt/jboss/keycloak/standalone/deployments/my-remote-user-storage-provider.jar

  user-legacy-service:
    image: artarkatesoft/oauth20-user-legacy-service
    depends_on:
      - keycloak

