server:
  port: 8080

app.services.orders.uri: http://orders-service:8091/orders

app.redirect.host.uri: http://127.0.0.1:${server.port}

app.oauth.uri: http://auth-server:8000
app.oauth.baseUri: ${app.oauth.uri}

spring:
  security:
    oauth2:
      client:
        registration:
          orders-web-oauth-client:
            clientId: client1
            clientSecret: ${CLIENT_SECRET:myClientSecretValue}
            scope:
              - openid
              - read
              - authorities
              - profile
            redirectUri: ${app.redirect.host.uri}/login/oauth2/code/orders-web-oauth-client
            authorizationGrantType: authorization_code
        provider:
          orders-web-oauth-client:
            issuerUri: ${app.oauth.baseUri}
logging:
  level:
    net.shyshkin: debug
#    org.springframework.security: trace
#    org.springframework.web.client: trace

---
spring:
  config:
    activate:
      on-profile: local

app.oauth.uri: http://localhost:8000
app.services.orders.uri: http://localhost:8091/orders